/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SXyePBR9qvC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Button } from "~/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "~/components/ui/card"
import React, { useState, useEffect} from "react"

export function Marketplace() {
  const [itemsMarket, setItemMarket] = useState([]);
  useEffect(() => {
    fetchCredits();
  }, []);
  
  const fetchCredits = async () => {
    try {
      const response = await fetch('http://localhost:8080/credit'); 
      const data = await response.json();
      setItemMarket(data);
      console.log(data);
    } catch (error) {
      console.error('Lỗi khi lấy dữ liệu:', error);
    }
  };
  return (
    <div className="min-h-screen bg-gray-100">
      <main className="container mx-auto p-4">
        <h1 className="text-2xl font-bold mb-4">Available Carbon Credits</h1>
        <div className="grid gap-4 md:grid-cols-3">
        {itemsMarket.map((item)=>(
          <div key={item.id}>
           <Card className="shadow-md h-full grid grid-rows-1">
            <CardHeader>
              <CardTitle>{item.title}</CardTitle>
              <CardDescription>{item.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-xl font-bold">{"$"+item.price}</div>
              <div className="text-sm text-muted-foreground">{item.amount+" available"}</div>
            </CardContent>
            <CardFooter className="flex justify-center">
              <Button className="w-full bg-green-700 text-white">Buy Now</Button>
            </CardFooter>
            </Card>   
          </div>
        ))}
        
      </div>
      </main>
    </div>
  )
}
// export function Marketplace({test}){
//   return(
//     <div className="bg-white">
      
//     </div>
//   );
// }

