/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SXyePBR9qvC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Avatar, AvatarImage, AvatarFallback } from "~/components/ui/avatar"
import Link from "next/link"
import { Button } from "~/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "~/components/ui/card"
import React, { SVGProps, useContext ,useState} from "react"
import {Header} from "~/components/component/header"
import { Myaccount } from "./myaccount"
import { Interface } from "readline"
type Item =  {
  id:number,
  title: string,
  description: string,
  price: number,
  amount: number,
  
}
type MarketplaceProps = {
  itemsMarket: Item[]; // Khai báo props 'items' là một mảng các Item
}
const item = {
  id:1,
  title: "Renewable Energy",
  description: "energy carbon credits from a wind farm project",
  price: 15.99,
  amount: 1000,
}
export function Marketplace({itemsMarket = []}: MarketplaceProps) {
  return (
    <div className="min-h-screen bg-gray-100">
      <main className="container mx-auto p-4">
        <h1 className="text-2xl font-bold mb-4">Available Carbon Credits</h1>
        <div className="grid gap-4 md:grid-cols-3">
        {itemsMarket.map((item)=>(
          <div key={item.id}>
           <Card className="shadow-md">
            <CardHeader>
              <CardTitle>{item.title}</CardTitle>
              <CardDescription>{item.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="text-xl font-bold">{"$"+item.price}</div>
              <div className="text-sm text-muted-foreground">{item.amount+" available"}</div>
            </CardContent>
            <CardFooter>
              <Button className="w-full bg-green-700 text-white">Buy Now</Button>
            </CardFooter>
            </Card>   
          </div>
        ))}
        
      </div>
      </main>
    </div>
  )
}
// export function Marketplace({test}){
//   return(
//     <div className="bg-white">
      
//     </div>
//   );
// }

