/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Om7q9EDgQ9Q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "~/components/ui/button"
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Textarea } from "~/components/ui/textarea"
import { Avatar, AvatarImage, AvatarFallback } from "~/components/ui/avatar"
import { JSX, SVGProps } from "react"
import {Header} from "~/components/component/header"
import Head from "next/head"
export function Mint() {
  
  return (
    <div className="min-h-screen bg-white">
      <main className="flex flex-col items-center py-8">
        <h1 className="text-3xl font-bold text-[#1E834B] mb-4">Mint Your Asset</h1>
        <section className="w-full max-w-2xl p-4">
          <h2 className="text-xl font-semibold mb-2">Upload Your Credit Carbon</h2>
          <div className="border-2 border-dashed border-gray-400 p-8 mb-4 text-center">
            <p className="text-gray-500 mb-4">UPLOAD YOUR CARBON CREDITS</p>
            <Button className="bg-[#1E834B] text-white">Upload</Button>
          </div>
          <div className="mb-4">
            <Label htmlFor="title" className="block mb-1">
              Your Title
            </Label>
            <Input id="title" placeholder="Enter your title" className="w-full" />
          </div>
          <div className="mb-4">
            <Label htmlFor="description" className="block mb-1">
              Description
            </Label>
            <Textarea id="description" placeholder="Description of the PNG" className="w-full" />
          </div>
          <div className="mb-4 flex items-center space-x-3">
            <Label htmlFor="quantity" className="block">
              Quantity:
            </Label>
            <Input id="quantity" type="number" className="w-25 text-center" defaultValue={1} />
          </div>
          <Button className="bg-[#1E834B] text-white w-full">Mint</Button>
        </section>
      </main>
    </div>
  )
}
